# Generated by Django 4.1.7 on 2023-04-23 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("experiences", "0002_experience_category_alter_perk_detail_and_more"),
        ("rooms", "0006_alter_room_amenities_alter_room_category_and_more"),
        ("wishlists", "0002_alter_wishlist_exeriences_alter_wishlist_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="exeriences",
            field=models.ManyToManyField(
                blank=True, related_name="wishlists", to="experiences.experience"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="rooms",
            field=models.ManyToManyField(
                blank=True, related_name="wishlists", to="rooms.room"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
